export const PAYMENT_SUCCEEDED_TOPIC = 'payment.succeeded' as const;
export type EventEnvelope<T> = { version: 1; eventId: string; occurredAt: string; payload: T };
export type InitiatePaymentRequest = { purchaseId: string };
export type PaymentStatus = "PENDING" | "SUCCESS" | "FAILED" | "CANCELLED";
export type PaymentOrder = { id: string; orderId: string; amount: string; currency: string; status: PaymentStatus };
export type PaymentResult = { status: PaymentStatus; paymentId?: string; purchaseId: string; ticketId?: string };
export type TicketStatus = 'ISSUED' | 'IN_JOURNEY' | 'COMPLETED' | 'EXPIRED';
export type JourneyStatus = 'ACTIVE' | 'COMPLETED' | 'TIMED_OUT';
export type GateType = 'ENTRY' | 'EXIT';
export type GateStatus = 'ACTIVE' | 'INACTIVE';
export type StationRef = { id: string; code: string; name: string };
export type GateRef = { id: string; code: string; type: GateType; status: GateStatus };
export type GateValidationRequest = { gateId: string; ticketIdentifier: string };
export type GateDecision = "ALLOW" | "REJECT";
export type GateValidationResult = {
  decision: GateDecision;
  rejectionCode?: string;
  message?: string;
  journey?: Pick<Journey, "id" | "enteredAt" | "expiresAt" | "exitedAt">;
};
export type RouteStation = StationRef & { lineOrder: number; gates: GateRef[] };
export type TicketRoute = { origin: StationRef; destination: StationRef; stations: RouteStation[] };
export type Ticket = {
  id: string;
  identifier: string;
  status: TicketStatus;
  paidAmount: string;
  currency: string;
  expiresAt: string;
  originStation: StationRef;
  destinationStation: StationRef;
};
export type Journey = { id: string; ticketId: string; status: JourneyStatus; entryStation: StationRef; actualExitStation: StationRef | null; entryGateId: string; exitGateId: string | null; enteredAt: string; expiresAt: string; exitedAt: string | null; timedOutAt: string | null };
