"use client";
import { useState } from "react";
import { setAccessToken } from "../auth-client";
import { Toast } from "../toast";

export default function OtpPage() {
  const [email, setEmail] = useState(""); const [code, setCode] = useState(""); const [sent, setSent] = useState(false); const [error, setError] = useState(""); const api = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:3001";
  async function submit(e: React.FormEvent) { e.preventDefault(); setError(""); const path = sent ? "/api/v1/auth/otp/verify" : "/api/v1/auth/otp/request"; const body = sent ? { email, code } : { email }; const r = await fetch(api + path, { method: "POST", headers: { "content-type": "application/json" }, credentials: "include", body: JSON.stringify(body) }); const data = await r.json(); if (!r.ok) { setError(data.message ?? "Unable to continue."); return; } if (!sent) setSent(true); else { setAccessToken(data.accessToken); window.location.assign(["ADMIN", "OPERATOR"].includes(data.user?.role) ? "/admin" : "/dashboard"); } }
  return <main className="auth-shell"><section className="auth-visual"><div className="brand">MetroFlow</div><div className="visual-copy"><h1>Sign in with a code.</h1><p>Use a one-time code sent to your registered email.</p></div></section><section className="auth-panel"><div className="auth-card">{error && <Toast message={error} onClose={() => setError("")} />}<div className="eyebrow">Email OTP</div><h2>{sent ? "Enter your code" : "Request a code"}</h2><p className="subtle">{sent ? "Check your inbox and enter the six-digit code." : "We will send a temporary login code."}</p><form onSubmit={submit}><label className="field" htmlFor="otp-email">Email<input id="otp-email" name="email" required type="email" value={email} onChange={e => setEmail(e.target.value)} /></label>{sent && <label className="field" htmlFor="otp-page-code">Email OTP<input id="otp-page-code" name="code" required inputMode="numeric" pattern="[0-9]{6}" maxLength={6} value={code} onChange={e => setCode(e.target.value.replace(/\D/g, ""))} /></label>}<button className="primary">{sent ? "Verify code" : "Send login code"}</button></form><p className="auth-link"><a href="/login">Back to sign in</a></p></div></section></main>;
}
