"use client";
import { useCallback, useEffect, useState } from "react";
import { AppShell } from "../../app-shell";
import { getAccessToken, refreshAccessToken } from "../../auth-client";
const api = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:3001";
type Ticket = { id: string; email: string; originStation: { name: string }; destinationStation: { name: string }; paidAmount: string; currency: string; status: string; expiresAt: string };
export default function AdminTicketsPage() {
  const [tickets, setTickets] = useState<Ticket[]>([]), [page, setPage] = useState(1), [pages, setPages] = useState(1), [status, setStatus] = useState(""), [query, setQuery] = useState(""), [search, setSearch] = useState(""), [sortBy, setSortBy] = useState("createdAt"), [direction, setDirection] = useState("desc"), [state, setState] = useState<"loading" | "error" | "ready">("loading"), [error, setError] = useState("");
  const load = useCallback(async () => { setState("loading"); setError(""); try { const token = getAccessToken() ?? await refreshAccessToken(); if (!token) throw new Error("Your operations session has expired."); const q = new URLSearchParams({ page: String(page), pageSize: "25", sortBy, sortDirection: direction }); if (status) q.set("status", status); if (query) q.set("search", query); const response = await fetch(`${api}/api/v1/tickets/operations?${q}`, { credentials: "include", headers: { authorization: `Bearer ${token}` } }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.message ?? "Unable to load tickets."); setTickets(body.data.tickets ?? []); setPages(body.data.pagination.totalPages || 1); setState("ready"); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load tickets."); setState("error"); } }, [page, status, query, sortBy, direction]);
  useEffect(() => { void load(); }, [load]);
  return <AppShell eyebrow="Administration"><div className="admin-header"><span className="sim-kicker">OPERATIONS</span><h1 className="page-title">Ticket operations</h1><p>Search, filter, and sort passenger tickets.</p></div><div style={{ display: "flex", gap: 12, flexWrap: "wrap", marginBottom: 16 }}><input aria-label="Search tickets" placeholder="Email, ticket ID, or purchase ID" value={search} onChange={e => setSearch(e.target.value)} /><button className="button" onClick={() => { setQuery(search); setPage(1); }}>Search</button><select aria-label="Filter ticket status" value={status} onChange={e => { setStatus(e.target.value); setPage(1); }}><option value="">All statuses</option><option value="ISSUED">Issued</option><option value="IN_JOURNEY">In journey</option><option value="COMPLETED">Completed</option><option value="EXPIRED">Expired</option></select><select aria-label="Sort tickets" value={sortBy} onChange={e => setSortBy(e.target.value)}><option value="createdAt">Newest</option><option value="expiresAt">Expiry</option><option value="status">Status</option><option value="email">Passenger</option></select><button className="button secondary" onClick={() => setDirection(v => v === "asc" ? "desc" : "asc")}>{direction === "asc" ? "Ascending" : "Descending"}</button></div>{state === "loading" && <p className="admin-notice">Loading tickets...</p>}{state === "error" && <div className="admin-notice error"><p>{error}</p><button className="button" onClick={() => void load()}>Retry</button></div>}{state === "ready" && tickets.length === 0 && <p className="admin-notice">No tickets match the selected filters.</p>}{state === "ready" && tickets.length > 0 && <><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Passenger</th><th>Route</th><th>Fare</th><th>Status</th><th>Expires</th></tr></thead><tbody>{tickets.map(t => <tr key={t.id}><td>{t.email}</td><td><strong>{t.originStation.name} → {t.destinationStation.name}</strong></td><td>{t.currency} {t.paidAmount}</td><td><span className="admin-tag">{t.status}</span></td><td>{new Date(t.expiresAt).toLocaleString()}</td></tr>)}</tbody></table></div><div style={{ display: "flex", justifyContent: "space-between", marginTop: 16 }}><span>Page {page} of {pages}</span><div><button className="button secondary" disabled={page <= 1} onClick={() => setPage(v => v - 1)}>Previous</button> <button className="button" disabled={page >= pages} onClick={() => setPage(v => v + 1)}>Next</button></div></div></>}</AppShell>;
}
